#!/bin/bash
alarmActivationHosts=android-749c6d221839e2bb$,android-ce6957237c1facc8

statusout=false
arr=$(echo $alarmActivationHosts | tr "," "\n")
for x in $arr
do
status=`ping -c 1 -w 1 $x`
if grep -q " 0% packet loss.*" <(echo $status);
then
statusout=true
fi
done
echo $statusout
