#!/bin/bash
function readConf {
shopt -s extglob
while IFS='= ' read lhs rhs
do
    if [[ $line != *( )#* ]]
    then
        # you can test for variables to accept or other conditions here
        declare -g $lhs=$rhs
    fi
done < /home/pi/security/security.conf
}


readConf
statusout=false;

arr=$(echo $alarmActivationHosts | tr "," "\n")
for x in $arr
do
status=`ping -c 1 -w 1 $x`
if grep -q " 0% packet loss.*" <(echo $status);
then
statusout=true
fi
done
echo $statusout
