#!/bin/bash
cd /home/pi/security/
function readConf {
shopt -s extglob
while IFS='= ' read lhs rhs
do
    if [[ $line != *( )#* ]]
    then
        # you can test for variables to accept or other conditions here
        declare -g $lhs=$rhs
    fi
done < security.conf
}

function checkStatus {
if [ "$1" = "open" ]
then
#sleep 2
alarm=`./checkHostStatus`
if [ "$manualOverride" = "true" ] || [ "$manualOverride$alarm" = "falsefalse" ] 
then
message="$2 is $1 and the alarm is on"
echo $message
echo `date`
bash ./sendGtalk "$message" &
fi
fi
}

#start of program
readConf
echo "Starting program " . `date`
gpio export 22 in
gpio export 23 in
gpio export 24 in
while(true)
do
#checkStatus BackDoor
backDoorStatus=`./checkStatusDoor 23`
garageDoorStatus=`./checkStatusDoor 24`
frontDoorStatus=`./checkStatusDoor 22`

checkStatus $backDoorStatus "Back Door"
checkStatus $garageDoorStatus "Garage Door"
checkStatus $frontDoorStatus "Front Door"

#sleep for a second
sleep 1
done

